<?php 
$recipe = $this->getRecipe();
$_helper = $this->helper('catalog/output');
$reviews = $this->getReviews();
?>
<style>
.recipe-left		{float: left; width: 275px;}
.recipe-left #main-recipe-img	{padding: 3px; margin-top: 3px; border: 1px solid #000000;}
.nut-title {color: #7A7A7A; font-size: 14px; margin-bottom: 10px; margin-top: 13px;}
.recipe-mid		{float: left; width: 450px; margin:10px 0px 0px 0px;}
.recipe-mid h3	{color: #7A7A7A; font-size: 14px; margin-bottom: 10px; margin-top: 13px;}
.recipe-mid ul 	{list-style: none; margin: 3px 0px 5px 0px;}
.recipe-right		{float: left; width: 160px; margin:0px 0px 0px 15px;}
.recipe-right h4	{color: #7A7A7A; font-size: 12px; margin-bottom: 10px;}
.recipe-list li	{margin-bottom: 15px;}
.recipe-right .actions {margin-top: 5px;}
.specs				{width:100%; padding-top: 0px; margin-top: 0px;}
#specs-left			{float:left; width:78px; height: 30px; border-right: #ccc 1px solid; padding-top: 15px; text-align: center;}
#specs-middle		{float:left; width:78px; height: 30px; padding-top: 15px; text-align: center;}
#specs-right		{float:left; width:78px; height: 30px; border-left: #ccc 1px solid; padding-top: 15px; text-align: center;}
.nut-label			{width: 100px; float:left;}

</style>
<div itemscope itemtype="http://schema.org/Recipe">
	<div class="recipe-left">
		<h3 itemprop="name"><?php echo $recipe->getTitle() ?></h3>
		<div class="ratings">
	        <div class="rating-box">
	        	<?php $rating = $recipe->getRateTotal() / $recipe->getRateCount() * 20 ?>
	            <div style="width:<?php echo round($rating) ?>%" class="rating"></div>
	        </div>
	        <p class="rating-links">
	            <a href="#recipe-review-achor"><?php echo count($reviews) ?> Review(s)</a>
	        </p>
	    </div>
		<!-- AddThis Button BEGIN -->
	<div class="addthis_toolbox addthis_default_style ">
	<a class="addthis_button_preferred_1"></a>
	<a class="addthis_button_preferred_2"></a>
	<a class="addthis_button_preferred_3"></a>
	<a class="addthis_button_preferred_4"></a>
	<a class="addthis_button_compact"></a>
	<a class="addthis_counter addthis_bubble_style"></a>
	</div>
	<script type="text/javascript" src="http://s7.addthis.com/js/300/addthis_widget.js#pubid=xa-507f82034e41cca7"></script>
	<!-- AddThis Button END --><br />
		<img itemprop="image" id="main-recipe-img" src="<?php echo Mage::getBaseUrl('media') ?>recipe/<?php echo $recipe->getLrgPath() ?>" />
		<div class="specs">
			<span class="nut-label">Difficulty:</span><?php echo $this->getDifficultyVal($recipe->getDifficulty()) ?><br />
			<span class="nut-label">Prep Time:</span><meta itemprop="prepTime" content="<?php echo $this->getIsoFormatTime($recipe->getPrepTime(), $recipe->getPrepTimeUnit())  ?>"><?php echo $recipe->getPrepTime() . " " . $this->getTimeVal($recipe->getPrepTimeUnit()) ?><br />
			<span class="nut-label">Cook Time:</span><meta itemprop="cookTime" content="<?php echo $this->getIsoFormatTime($recipe->getCookTime(), $recipe->getCookTimeUnit())  ?>"><?php echo $recipe->getCookTime() . " " . $this->getTimeVal($recipe->getCookTimeUnit()) ?><br />
			<span class="nut-label">Serves:</span><span itemprop="recipeYield"><?php echo $recipe->getServings() ?></span><br />
		</div>
		
		<div id="nutritional-info" itemprop="nutrition" itemscope itemtype="http://schema.org/NutritionInformation">
			<h3 class="nut-title">Nutritional Information</h3>
			<?php if($recipe->getCalories()): ?>
				<span class="nut-label">Calories:</span><span itemprop="calories"><?php echo $recipe->getCalories() ?></span><br />
			<?php endif ?>
			<?php if($recipe->getCarbohydrateContent()): ?>
				<span class="nut-label">Carbohydrates:</span><span itemprop="carbohydrateContent"><?php echo $recipe->getCarbohydrateContent() ?> grams</span><br />
			<?php endif ?>
			<?php if($recipe->getCholesterolContent()): ?>
				<span class="nut-label">Cholesterol:</span><span itemprop="cholesterolContent"><?php echo $recipe->getCholesterolContent() ?> milligrams</span><br />
			<?php endif ?>
			<?php if($recipe->getFatContent()): ?>
				<span class="nut-label">Fat:</span><span itemprop="fatContent"><?php echo $recipe->getFatContent() ?></span> grams<br />
			<?php endif ?>
			<?php if($recipe->getFiberContent()): ?>
				<span class="nut-label">Fiber:</span><span itemprop="fiberContent"><?php echo $recipe->getFiberContent() ?></span> grams<br />
			<?php endif ?>
			<?php if($recipe->getProteinContent()): ?>
				<span class="nut-label">Protein:</span><span itemprop="proteinContent"><?php echo $recipe->getProteinContent() ?></span> grams<br />
			<?php endif ?>
			<?php if($recipe->getSaturatedFatContent()): ?>
				<span class="nut-label">Saturated Fat:</span><span itemprop="saturatedFatContent"><?php echo $recipe->getSaturatedFatContent() ?></span> grams<br />
			<?php endif ?>
			<?php if($recipe->getServingSize()): ?>
				<span class="nut-label">Serving Size:</span><span itemprop="servingSize"><?php echo $recipe->getServingSize() ?></span><br />
			<?php endif ?>
			<?php if($recipe->getSodiumContent()): ?>
				<span class="nut-label">Sodium:</span><span itemprop="sodiumContent"><?php echo $recipe->getSodiumContent() ?></span> milligrams<br />
			<?php endif ?>
			<?php if($recipe->getSugarContent()): ?>
				<span class="nut-label">Sugar:</span><span itemprop="sugarContent"><?php echo $recipe->getSugarContent() ?></span> grams<br />
			<?php endif ?>
			<?php if($recipe->getTransFatContent()): ?>
				<span class="nut-label">Trans Fat:</span><span itemprop="transFatContent"><?php echo $recipe->getTransFatContent() ?></span> grams<br />
			<?php endif ?>
			<?php if($recipe->getUnsaturatedFatContent()): ?>
				<span class="nut-label">Unsaturated Fat:</span><span itemprop="unsaturatedFatContent"><?php echo $recipe->getUnsaturatedFatContent() ?></span> grams<br />
			<?php endif ?>
		</div>
	</div>
	
	<div class="recipe-mid">
	<p itemprop="description"><?php echo $recipe->getDesc() ?></p>
	<h3>Ingredients</h3>
		<ul>
		<?php foreach($this->getIngredients($recipe->getId()) as $ing): ?>
			<?php if($ing->getSku()): ?>
				<?php $product = Mage::getModel('catalog/product')->loadByAttribute('sku',$ing->getSku()) ?>
			<?php endif ?>
			<li itemprop="ingredients">
				<?php echo $ing->getMeasure() . " " ?>
				<?php if($ing->getSku()): ?>
					<a href="<?php echo $product->getProductUrl() ?>"><?php echo $ing->getIngredient() ?></a>
				<?php else: ?>
					<?php echo $ing->getIngredient() ?>
				<?php endif ?>
			</li>
		<?php endforeach ?>
		</ul>
		<div style="border-top: 1px #ccc dotted; width: 450px; margin-top: 20px;"></div>
	<h3>Directions</h3>
		<ul itemprop="recipeInstructions">
		<?php $count = 1 ?>
		<?php foreach($this->getSteps($recipe->getId()) as $step): ?>
			<li><?php echo $count++ . ". " . $step->getStep() ?></li>
		<?php endforeach ?>
		</ul>
		
		<div style="border-top: 1px #ccc dotted; width: 450px; margin-top: 20px;"></div>
		<h3>Rate this Recipe</h3>
		<form id="rate-recipe" action="<?php echo Mage::getBaseUrl('web') ?>recipe/index/rate" method="get">
			<table id="product-review-table" class="data-table" style="width:340px;">
		        <colgroup>
		        <col width="1">
		        <col width="1">
		        <col width="1">
		        <col width="1">
		        <col width="1">
		        </colgroup><thead>
		            <tr class="first last">
		                <th><span class="nobr">1 star</span></th>
		                <th><span class="nobr">2 stars</span></th>
		                <th><span class="nobr">3 stars</span></th>
		                <th><span class="nobr">4 stars</span></th>
		                <th><span class="nobr">5 stars</span></th>
		            </tr>
		        </thead>
		        <tbody>
		        	<tr class="first odd">
		            	<td class="value"><input type="radio" class="radio" value="1" id="Quality_1" name="rating"></td>
		                <td class="value"><input type="radio" class="radio" value="2" id="Quality_2" name="rating"></td>
		                <td class="value"><input type="radio" class="radio" value="3" id="Quality_3" name="rating"></td>
		                <td class="value"><input type="radio" class="radio" value="4" id="Quality_4" name="rating"></td>
		                <td class="value last"><input type="radio" class="radio" value="5" id="Quality_5" name="rating"></td>
		            </tr>
		        </tbody>
		    </table><br />
	        <input type="hidden" name="recipe_id" value="<?php echo $recipe->getId() ?>" />
	        <button type="button" type="submit" onclick="submitForm();" class="button"><span><span><?php echo $this->__('Rate this Recipe') ?></span></span></button>
		</form>
		<script>
		function submitForm() {
			$('rate-recipe').submit();
		}
		</script>
		
	<?php $reviews = $this->getReviews() ?>
	<?php if(count($reviews)): ?>
		<h3 id="recipe-review-achor">Reviews</h3>
		<?php foreach($this->getReviews() as $review): ?>
			<div>
				<div class="review-name" style="float:left; width:50px; "><?php echo $review->getReviewName() ?></div>
				<div class="review-text" style="float:left; width:380px; margin-left:20px;"><?php echo $review->getReviewText() ?></div>
				<div class="review-date" style="float:left; width:450px; text-align:right; margin-bottom:20px;">
					<div style="border-top: 1px #ccc dotted; width: 380px; margin-top: 5px; margin-left:70px;"></div>
					<?php echo date('m-d-Y \a\t h:i A', strtotime($review->getCreatedAt())) ?>
				</div>
			</div>
		<?php endforeach ?>
	<?php endif ?>
		
		<!-- form for adding review -->
		<div style="float:left; width:450px;">
			<form method="post" id="reviewForm" action="<?php echo Mage::getBaseUrl('web') ?>recipe/index/review">
			    <div class="fieldset" style="margin-bottom:10px;">
			        <h2 class="legend">Submit Review</h2>
			        <ul class="form-list">
			            <li class="fields">
			                <div class="field">
			                    <label class="required" for="name"><em>*</em>Name</label>
			                    <div class="input-box">
			                        <input type="text" class="input-text required-entry" value="" title="Name" id="name" name="name">
			                    </div>
			                </div>
			                <div class="field">
			                    <label class="required" for="email"><em>*</em>Email</label>
			                    <div class="input-box">
			                        <input type="text" class="input-text required-entry validate-email" value="" title="Email" id="email" name="email">
			                    </div>
			                </div>
			            </li>
			            <li class="wide">
			                <label class="required" for="comment"><em>*</em>Comment</label>
			                <div class="input-box" style="width:390px;">
			                    <textarea style="width:390px;" rows="3" cols="5" class="required-entry input-text" title="Comment" id="comment" name="comment"></textarea>
			                </div>
			            </li>
			        </ul>
			    </div>
			    <div class="buttons-set" style="padding-top:5px; margin:0px;">
			    	<input type="hidden" name="recipe_id" value="<?php echo $recipe->getId() ?>" />
			        <input type="text" style="display:none !important;" value="" id="hideit" name="hideit">
			        <button class="button" title="Submit" type="submit"><span><span>Submit</span></span></button>
			    </div>
			</form>
			<script type="text/javascript">
			//<![CDATA[
			    var reviewForm = new VarienForm('reviewForm', true);
			//]]>
			</script>
		</div>
	</div>
	
	<div class="recipe-right">
		<?php if($recipe->getSkus()): ?>
		<h4>Products in this Recipe</h4>
		<ul class="recipe-list">
		<?php $x = 0 ?>
		<?php $simple = true ?>
		<?php $productStr = '' ?>
		<?php foreach($this->getRecipeProducts($recipe->getSkus()) as $_product): ?>
			<?php $x++ ?>
			<?php if($_product[0]->getTypeId() != 'simple' || !$_product[0]->isSalable()): ?>
				<?php $simple = false ?>
			<?php endif ?>
			<?php if($x != 1) $productStr .= ',' ?>
			<?php $productStr .= $_product[0]->getId() . ':' . $_product[1] ?>
			<li class="item">
			    <a class="product-image" title="<?php echo $this->stripTags($this->getImageLabel($_product[0], 'small_image'), null, true) ?>" href="<?php echo $_product[0]->getProductUrl() ?>"><img width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product[0], 'small_image'), null, true) ?>" src="<?php echo $this->helper('catalog/image')->init($_product[0], 'small_image')->resize(135); ?>"></a>
			    <h2 class="product-name"><a title="<?php echo $this->stripTags($this->getImageLabel($_product[0], 'small_image'), null, true) ?>" href="<?php echo $_product[0]->getProductUrl() ?>"><?php echo $_helper->productAttribute($_product[0], $_product[0]->getName() , 'name'); ?></a></h2>
			    <div class="actions">
			    	<p>
					<?php if($_product[0]->isSaleable()): ?>
	                        <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product[0]) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>  
	                    <?php else: ?>
	                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
	                <?php endif; ?>
	                	<button type="button" title="<?php echo $this->__('View') ?>" class="button btn-cart" onclick="setLocation('<?php echo $_product[0]->getProductUrl() ?>')"><span><span><?php echo $this->__('View') ?></span></span></button>
	                </p>
			    </div>
			</li>
	
		<?php endforeach ?>
			<?php if($x > 1 && $simple): ?>
				<button type="button" title="<?php echo $this->__('Add All to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo Mage::getBaseUrl('web') . 'recipe/index/addallcart/products/' . $productStr ?>')"><span><span><?php echo $this->__('Add Recipe to Cart') ?></span></span></button> 
			<?php endif ?>
		</ul>
		<?php endif ?>
	</div>
</div>